### ISSUE TITLE
Kef LSX

### ISSUE THREAD

**Issue by doekwerk** [basnijholt/aiokef#4]
Kef LSX uses some different inputs which leads to a fail.
i.e. Wifi returns the status 2.
I will test the status codes for the LSX tomorrow.

**Comment by basnijholt** [comment]
Ah, great to hear that you are trying the library!

I don't own a LSX. Could you tell me what inputs there are?

**Comment by doekwerk** [comment]
Wifi, Bluetooth, Aux, Opt.
<img width="375" alt="PNG-afbeelding" src="https://user-images.githubusercontent.com/23216889/69834999-71847580-123e-11ea-8fbc-fd30fb5be4ba.png">

But I believe there are also status codes for AirPlay and SpotifyConnect.

The basics work!

**Comment by basnijholt** [comment]
What do you mean with the basics?

And what specifically doesn't work?

**Comment by doekwerk** [comment]
Hi Bas, I am not a coder but a hardware engineer with some linux experience. I can debug a little and hope to provide you some help.

I am trying your media_player.py with KEF LSX on Hassio.
LSX latest Firmware: p20.4101909240.105243422.
media_player.py is in my config/custom_components/kef
aiokef was not installed automatically after several restarts so I installed aiokef from the Hassio add-on Configurator Execute_Shell_Command with:
pip3 install --target /config --no-dependencies aiokef

aiokef 0.1.8 is installed.

mediaplayer.kef didn't work as expected but the log showed that there as hope!

In aiokef.py I changed the inputs set to:
`#INPUT_SOURCES = {"Wifi": 18, "Bluetooth": 25, "Aux": 26, "Opt": 27, "Usb": 28}`
`INPUT_SOURCES = {"Wifi": 2, "Bluetooth": 9, "Aux": 10, "Opt": 11}`

With these settings this works from within Hassio:
- Mute and unmute
- Get and set source input
- Turn speaker on and off

Changing Volume within Hassio doesn't work correct:
When the LSX is turned on with mediaplayer.kef the volume is synchronized correct. When changed again it becomes out of sync and doesn't work anymore.

Below the logs from turning on and adjusting volume:

The aiokef.log is from a turn on and volume change from within hassio
[aiokef.log](https://github.com/basnijholt/aiokef/files/3905313/aiokef.log)

This is a tcpdump from about the same action from the keffapp:
[kefapp_cap.log](https://github.com/basnijholt/aiokef/files/3905459/kefapp_cap.log)

**Comment by kraih** [comment]
Actually it's not that the protocol is different between the LS50W and the LSX, it's just that you're decoding the input source incorrectly. I've recently spent a few hours reverse engineering the protocol, and it turns out there is some more information hidden in the packet. Only bits 0-3 are the input source, rest is stand by time, inverse mode and power on/off. You're welcome to take a look at [kefctl](https://github.com/kraih/kefctl) for more details.

**Comment by kraih** [comment]
Btw. I have not seen a special indicator for AirPlay and Spotify Connect yet.

**Comment by doekwerk** [comment]
Nice decoding Kraih! I like the bit approach in your work. I can understand it :)

**Comment by basnijholt** [comment]
@kraih, great work!

I will take a look and will make the appropriate changes.

**Comment by basnijholt** [comment]
@doekwerk and @kraih,

I have created https://github.com/basnijholt/aiokef/pull/5 where I implement your findings!

In addition, I think I found two things you do not have implemented yet. Specifically, turning on the speaker on its old source (which is just +128 on the source number) and that bluetooth has a different number when paired.

@doekwerk, your LSXs should work fine now :tada: might I ask how you found the repo?

**Comment by basnijholt** [comment]
@doekwerk, could you try https://github.com/basnijholt/media_player.kef in Home-Assistant again?

I have made some updates to it. Make sure to update `aiokef` to v0.2.0 and change your HA config entry to:
```
media_player:
  - platform: kef
    host: 192.168.x.x  # the IP of your speaker
    type: LSX
```

You can now also set the standby time and invert the speakers, see [this](https://github.com/basnijholt/media_player.kef#configure).

It would be *REALLY* great if you can try it because I've added this code as PR to Home-Assistant here: https://github.com/home-assistant/home-assistant/pull/28959. You could confirm that it works for the LSX 🎉

**Comment by basnijholt** [comment]
I have the KEF LSX speakers myself now too, and can confirm that it works 🎉

**Comment by doekwerk** [comment]
Sorry for not coming back in a while and answer. I also can conform ie works on the LSX.
Great job! And thx for your time making this.

**Comment by basnijholt** [comment]
Also, note that in Home-Assistant 0.104 we have the KEF integration!

**Comment by kraih** [comment]
I've reverse engineered the rest of the protocol now, including [DSP settings](https://github.com/kraih/kefctl/blob/master/kefdsp). If you're interested in any of that.

Btw. The mobile app is so terribly unresponsive because every little change triggers at least 8 request/response roundtrips to update all settings.

**Comment by basnijholt** [comment]
@kraih, thanks, that is really great! I will add these too!

I've also implemented pause and play and found two bugs (one is an inconsistency).

The first one (others with LS50s have been able to reproduce) is that when you put the speakers on a standby setting of 20 minutes, and turn them off, the speaker will not be able to turn on anymore,.

The second one is ([these lines](https://github.com/basnijholt/aiokef/blob/master/aiokef/aiokef.py#L59-L61)) that when the speaker is on Wifi, "R/L", 60 min, that the response isn't `82` but `48`, for no apparent reason.

Do you have an idea why that happens?

**Comment by kraih** [comment]
@basnijholt The first problem i can confirm with my LS50W (new electronics, latest firmware). They refuse to turn back on again. But for the second problem i do not see any inconsistencies here.
